services:
  - type: web
    name: chappy-v2
    env: node
    plan: free
    buildCommand: npm run predeploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 1337
      # Lägg till dina AWS och JWT secrets här i Render dashboard istället

